# Generated by Django 5.0.2 on 2025-10-25 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list, help_text='List of skills the user has')),
                ('wanted_skills', models.JSONField(default=list, help_text='List of skills the user wants to learn')),
                ('availability', models.JSONField(default=list, help_text='Days of week available')),
                ('time_slots', models.JSONField(default=list, help_text='Time slots available (morning, afternoon, evening)')),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('videos', models.JSONField(default=list, help_text='List of video URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
