# Generated by Django 5.0.2 on 2026-08-17 06:08

import config.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ringtone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(storage=config.cloudinary_storage.get_video_storage, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='ringtone',
            name='audio_file',
            field=models.FileField(storage=config.cloudinary_storage.get_raw_storage, upload_to='ringtones/'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='accounts_po_user_id_17e108_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post'], name='accounts_po_post_id_e5f885_idx'),
        ),
        migrations.AddIndex(
            model_name='postvideo',
            index=models.Index(fields=['post'], name='accounts_po_post_id_b009d2_idx'),
        ),
    ]
