# Generated by Django 5.0.2 on 2026-08-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('category', 'name', 'level')},
        ),
    ]
