# Generated by Django 5.0.2 on 2026-08-17 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_user', '-created_at'], name='skills_revi_reviewe_44a245_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='skills_revi_reviewe_6f2e51_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['from_user', 'status'], name='skills_sess_from_us_103804_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['to_user', 'status'], name='skills_sess_to_user_6d5f86_idx'),
        ),
    ]
