# Generated by Django 5.0.2 on 2026-08-18 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_chat_messag_sender__61a5fc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10)),
                ('outcome', models.CharField(choices=[('missed', 'Missed'), ('answered', 'Answered'), ('completed', 'Completed')], default='missed', max_length=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_delivered'], name='chat_messag_receive_f3a784_idx'),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='callee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['caller', '-started_at'], name='chat_callhi_caller__bf8f64_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['callee', '-started_at'], name='chat_callhi_callee__90e123_idx'),
        ),
    ]
